---
title: "p8105_hw2_yl5828"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r message = FALSE}
# Load dataset
library(tidyverse)
library(dplyr)
```


## Problem 1

### Clean file pols-month

```{r read and clean pols_month}
pols_month_df =
  read_csv("./fivethirtyeight_datasets/pols-month.csv", na = c("NA", ".", "")) %>%
  janitor::clean_names() %>%
  separate(mon, into = c("year", "month", "day"), sep = "-") %>%
  mutate(
    month=recode(month, `01` ="January", `02`= "February", `03`= "March", `04`= "April", `05`= "May",`06`= "June",`07`= "July",`08`= "August",`09`= "September",`10`= "October",`11`= "November",`12`= "December"),
    president = if_else(prez_gop == 1, "gop", "dem"),
    year = as.numeric(year)
         )%>%
  select(-prez_dem, -prez_gop, -day)

pols_month_df
```

### Clean file snp

```{r read and clean snp}
snp_df =
  read_csv("./fivethirtyeight_datasets/snp.csv", na = c("NA", ".", "")) %>%
  janitor::clean_names() %>%
  separate(date, into = c("month", "day", "year"), sep = "/") %>%
  mutate(
    month=recode(month, `1` ="January", `2`= "February", `3`= "March", `4`= "April", `5`= "May",`6`= "June",`7`= "July",`8`= "August",`9`= "September",`10`= "October",`11`= "November",`12`= "December"),
    year = if_else(year > 25, 1900 + as.numeric(year), 2000 + as.numeric(year)))%>%
  select(year, month, close)

snp_df
```

### Clean file unemployment

```{r read and clean unemployment}
unemployment_df = 
  read_csv("./fivethirtyeight_datasets/unemployment.csv", na = c("NA", ".", "")) %>%
  janitor::clean_names() %>%
  pivot_longer(
    jan:dec,
    names_to = "month", 
    values_to = "unemployment") %>%
  mutate(
    month=recode(month, `jan` ="January", `feb`= "February", `mar`= "March", `apr`= "April", `may`= "May",`jun`= "June",`jul`= "July",`aug`= "August",`sep`= "September",`oct`= "October",`nov`= "November",`dec`= "December" ))

unemployment_df
```

### Join datasets

```{r Join datasets}
q1join_df = 
  inner_join(pols_month_df, snp_df, by = c("year", "month")) %>%
  inner_join(unemployment_df, by = c("year", "month"))

q1join_df
```








